name: JFrog CI Pipeline
on: [push]

permissions:
  id-token: write
  contents: read

env:
  JFROG_CLI_BUILD_NAME: ${{ github.repository }}-build
  JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github-oidc-provider

      - name: Collect Build Metadata
        run: |
          jf rt build-collect-env
          jf rt build-add-git

      - name: Configure Maven
        run: |
          jf mvnc \
            --repo-resolve-releases  libs-release \
            --repo-resolve-snapshots libs-snapshot \
            --repo-deploy-releases   libs-release-local \
            --repo-deploy-snapshots  libs-snapshot-local

      - name: Build, Test and Deploy
        run: jf mvn clean deploy

      - name: Docker Build and Push
        run: |
          DOMAIN=$(echo "${{ secrets.JF_URL }}" | sed 's|https\?://||' | sed 's|/$||')
          IMAGE_TAG=$DOMAIN/docker-local/spring-petclinic:${{ github.run_number }}
          docker build -t $IMAGE_TAG .
          jf docker push $IMAGE_TAG --module=docker

      - name: Publish Build Info
        run: jf rt build-publish
